angular.module('randomizerConstants', []).constant('randomizerConstants', {
        companies: [
                {name: 'Uber', image: 'resources/imgs/uber.jpg'},
                {name: 'Lyft', image: 'resources/imgs/lyft.jpg'},
                {name: 'Amazon', image: 'resources/imgs/amazon.jpg'},
                {name: 'Netflix', image: 'resources/imgs/netflix.png'},
                {name: 'Wag', image: 'resources/imgs/wag.png'},
                {name: 'Ebay', image: 'resources/imgs/ebay.png'},
                {name: 'Draftkings', image: 'resources/imgs/draft.jpg'},
                {name: 'Facebook', image: 'resources/imgs/fb.png'},
                {name: 'Yelp', image: 'resources/imgs/yelp.jpg'},
                {name: 'Airbnb', image: 'resources/imgs/airbnb.jpg'},
                {name: 'Grindr', image: 'resources/imgs/grindr.jpg'},
                {name: 'Tinder', image: 'resources/imgs/tinder.jpg'},
                {name: 'Tesla', image: 'resources/imgs/tesla.png'},
                {name: 'Twitter', image: 'resources/imgs/twitter.png'},
                {name: 'Juicero', image: 'resources/imgs/juicero.png'},
                {name: 'Roman Health', image: 'resources/imgs/roman.jpg'},
                {name: 'Sling', image: 'resources/imgs/sling.jpg'},
                {name: 'Tiktok', image: 'resources/imgs/tiktok.jpg'},
                {name: 'NFL Redzone', image: 'resources/imgs/redzone.jpg'},
            ],
        nouns: [
                {name: 'dogs', image: 'resources/imgs/dog.jpg'},
                {name: 'buttholes', image: 'resources/imgs/censored.jpg'},
                {name: 'machine learning', image: 'resources/imgs/machinelearning.jpg'},
                {name: 'aglets', image: 'resources/imgs/aglets.jpg'},
                {name: 'room-temperature milk', image: 'resources/imgs/milk.jpg'},
                {name: 'awkward hellos', image: 'resources/imgs/awkwardhellos.jpg'},
                {name: 'racist grandmas', image: 'resources/imgs/grandmas.jpg'},
                {name: 'mullets', image: 'resources/imgs/mullets.jpg'},
                {name: 'the War of Northern Aggression', image: 'resources/imgs/lincoln.jpg'},
                {name: 'hot air balloon pilots', image: 'resources/imgs/balloons.jpg'},
                {name: 'anti-vaxers', image: 'resources/imgs/antivax.jpg'},
                {name: 'yoga balls', image: 'resources/imgs/yoga.jpg'},
                {name: 'pizza lovers', image: 'resources/imgs/pizza.jpg'},
                {name: 'professional wrestlers', image: 'resources/imgs/wrestlers.jpg'},
                {name: 'startup generators', image: 'resources/imgs/startup.png'},
                {name: 'Republicans', image:'resources/imgs/republicans.png'},
                {name: 'boomers', image: 'resources/imgs/boomers.jpg'},
        ],
        locations: [
                {name: 'in a modern world', image: 'resources/imgs/modern.jpg'},
                {name: 'at renaissance fairs', image: 'resources/imgs/renaissance.jpg'},
                {name: 'on a paleo diet', image: 'resources/imgs/caveman.jpg'},
                {name: 'in Kansas', image: 'resources/imgs/kansas.jpg'},
                {name: 'in space', image: 'resources/imgs/space.jpg'},
                {name: 'at family reunions', image: 'resources/imgs/reunion.jpg'},
                {name: 'at Coachella', image: 'resources/imgs/coachella.jpg'},
                {name: 'in a bear market', image: 'resources/imgs/bearmarket.jpg'},
                {name: 'on a boat', image: 'resources/imgs/onaboat.jpg'},
        ]
    });